application: gig-o-matic
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /bootstrap
  static_dir: bootstrap
  
- url: /datepicker
  static_dir: datepicker

- url: /css
  static_dir: css
  
- url: /images
  static_dir: images
  
- url: /.*
  script: main.application
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest